[package]
name = "derive-aktor"
version = "0.1.0"
authors = ["insanitybit <insanitybit@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "*"

fibers = "*"
futures = "*"
tokio = "0.1.21"

[dependencies.syn]
version = "*"
features = ['full']
