[package]
name = "derive-aktor"
version = "0.1.0"
authors = ["insanitybit <insanitybit@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "*"
futures = "*"
string_morph = "*"

[dependencies.channel]
git = "https://github.com/stjepang/channel"
rev = "949ce33946d9e4686386ebbbe022b71de9b20950"


[dependencies.syn]
version = "*"
features = ['full']